config/routes.rb
DBill::Application.routes.draw do

  resources :bills, :only => [:show, :create] do
    get :show, :as => 'join', :on => :collection
    resources :claims, :only => [:edit, :update]
  end

  root :to => 'application#root'
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  has_many :claims

  mount_uploader :receipt, ReceiptUploader


  before_create :generate_defaults

  def to_param
    code
  end

  def total=(val)
    self.total_cents = val.to_f * 100
  end

  def total
    total_cents / 100
  end

  def total_claimed
    claims.map(&:amount).reduce(:+)
  end

  def total_tip_claimed
    claims.map(&:tip_amount).reduce(:+)
  end

  private

  def generate_defaults
    generate_code
  end

  def generate_code
    random = rand(10000).to_s
    if Bill.exists?(:code => random)
      generate_code
    else
      self.code = random
    end
  end
end

app/models/claim.rb
class Claim < ActiveRecord::Base
  belongs_to :bill

  def amount=(value)
    self.amount_cents = (value.to_f * 100).to_i
  end

  def tip_amount=(value)
    self.tip_amount_cents = (value.to_f * 100).to_i
  end

  def amount
    amount_cents / 100.0
  end

  def tip_amount
    tip_amount_cents / 100.0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def root

  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  respond_to :json, :html

  def create
    @bill = Bill.create!(bill_params)
    redirect_to bill_path(@bill, name: params[:name])
  end

  def show
    redirect_to root_path if params[:name].blank?
    @bill = Bill.where(:code => params[:id]).first
    @claim = @bill.claims.find_or_create_by_name(params[:name])
    raise 'not_found' if @bill.nil?
  end

  private

  def bill_params
    params.require(:bill).permit(:total, :receipt)
  end

end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  def edit
    @claim = Claim.find(params[:id])
  end

  def create
  end

  def update
    claim = Claim.find(params[:id])
    claim.update_attributes(params.require(:claim).permit(:amount, :tip_amount))
    redirect_to bill_path(claim.bill, name: claim.name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/root.html.haml
= render 'pages/landing'
= render 'pages/create'
= render 'pages/join'

app/views/bills/show.html.haml
%div{:data => {:role => :page}, :id => "BILL#{@bill.id}"}
  %header{:data => {:role => :header}}
    %a.ui-btn-left{:href => '/', :data => {:icon => 'flat-menu', :iconpos => :notext, :theme => :b, :inline => :true, :corners => :true, :shadow => :true, :iconshadow => :true}}
    %h1= @bill.code
    - if @bill.receipt.present?
      %a.ui-btn-right{:href => "#RECEIPT#{@bill.id}", :data => {:rel => :dialog, :icon => 'flat-eye', :iconpos => :notext, :theme => :b, :inline => :true, :corners => :true, :shadow => :true, :iconshadow => :true}}
  .content{:data => {:role => :content}}
    %ul{:data => {:role => :listview, :inset => :true}}
      %li{:data => {:role => 'list-divider'}}
        .name All Claims
        .tip Tip
        .amount Amount
      - @bill.claims.each do |claim|
        %li
          .name= claim.name
          .tip= claim.tip_amount
          .amount= claim.amount
      %li{:data => {:role => 'list-divider'}}
        .name Total
        .tip= @bill.total_tip_claimed
        .amount= @bill.total_claimed
      %li{:data => {:role => 'list-divider', :theme => :d}}
        .name Missing
        .tip &nbsp;
        .amount= @bill.total - @bill.total_claimed
      %li{:data => {:role => 'list-divider'}}
        .name Target
        .tip #{"%.2f" % (@bill.total_tip_claimed.to_f / @bill.total * 100)}%
        .amount= @bill.total

    %a{:href => edit_bill_claim_path(@bill, @claim), :data => {:role => :button, :icon => 'flat-plus', :theme => :a, :iconshadow => :true}} Claim
  %div{:data => {:role => :'subpage-dialog'}, :id => "RECEIPT#{@bill.id}"}
    %header{:data => {:role => :header, :theme => :c}}
      %a.ui-btn-left{:data => {:rel => :back, :icon => 'flat-cross', :iconpos => :notext, :theme => :f, :inline => :true, :corners => :true, :shadow => :true, :iconshadow => :true}}
      %h1 Receipt Image
    .content#receipt_image_dialog{:data => {:role => :content}}
      %img{:src => @bill.receipt_url}

- unless request.xhr?
  = render :template => 'application/root'

app/views/claims/edit.html.haml
%div{:data => {:role => :page}, :id => "CLAIM#{@claim.id}"}
  %header{:data => {:role => :header}}
    %h1= @claim.bill.code
    - if @claim.bill.receipt
      %a.ui-btn-right{:href => @claim.bill.receipt_url, :data => {:ajax => :false, :icon => 'flat-eye', :iconpos => :notext, :theme => :b, :inline => :true, :corners => :true, :shadow => :true, :iconshadow => :true}}
  .content{:data => {:role => :content}}
    = form_tag bill_claim_path(@claim.bill, @claim), :method => :put, :data => {:ajax => :false} do
      %span Amount
      %input{:name => 'claim[amount]', :value => @claim.amount }
      %br
      %span Tip
      %input{:name => 'claim[tip_amount]', :value => @claim.tip_amount }
      %br
      = submit_tag 'Save'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:charset => 'utf-8'}
    %meta{:name => 'viewport', :content => 'initial-scale=1; user-scalable=no;'}
    %meta{:name => 'apple-mobile-web-app-capable', :content => 'yes'}

    %title D-Bill
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = yield

app/views/pages/_create.html.haml
#create{:data => {:role => :page}}
  %header{:data => {:role => :header}}
    %h1 Create Table
  .content{:data => {:role => :content}}
    = form_tag bills_path, :method => :post, :multipart => true, :data => {:ajax => :false} do
      %input{:name => 'name', :type => 'text', :placeholder => 'Your name'}
      %input{:name => 'bill[total]', :placeholder => 'Total price on the receipt (not including tip)'}
      .add-image
        %div{:data => {:role => :button, :theme => :a}}
          Add Image
        = file_field_tag 'bill[receipt]', :accept => 'image/*;capture=camera'
      %br
      = submit_tag 'Create Table'

app/views/pages/_join.html.haml
#join{:data => {:role => :page}}
  %header{:data => {:role => :header}}
    %h1 Join Table
  .content{:data => {:role => :content}}
    = form_tag join_bills_path, :method => :get do
      %input{:type => :number, :name => 'id', :placeholder => 'Enter the code'}
      %input{:type => :text, :name => 'name', :placeholder => 'Enter the code'}
      = submit_tag 'Join'

app/views/pages/_landing.html.haml
#landing{:data => {:role => :page}}
  %header{:data => {:role => :header}}
    %h1 D-Bill
  .content{:data => {:role => :content}}
    %a{:href => '#create', :data => {:role => :button}} Create Table
    %a{:href => '#join', :data => {:role => :button}} Join Table